USE exo_6_employes;


DROP TABLE IF EXISTS EMPLOYES;
DROP TABLE IF EXISTS LIVRAISONS;
DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS RAYONS;
DROP TABLE IF EXISTS FOURNISSEURS;

CREATE TABLE IF NOT EXISTS EMPLOYES
(
	code_E INT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
	salaire DECIMAL(6,2) NOT NULL,
	code_E_encadrant INT,
	nom_R VARCHAR(50) NOT NULL 	
);

CREATE TABLE IF NOT EXISTS RAYONS
(
	nom_R VARCHAR(50) PRIMARY KEY,
	etage INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLES
(
	code_A INT PRIMARY KEY,
	nom_A VARCHAR(50) NOT NULL,
	type_A CHAR(1) NOT NULL,
	nom_R VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FOURNISSEURS
(
	code_F INT PRIMARY KEY,
	adresse VARCHAR(250) NOT NULL,
	nom_F VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRAISONS
(
	code_F INT,
	code_A INT,
	quantite INT NOT NULL
);


ALTER TABLE EMPLOYES
ADD CONSTRAINT FK_code_E_encadrant FOREIGN KEY (code_E_encadrant) REFERENCES EMPLOYES (code_E),
ADD CONSTRAINT FK_nom_R FOREIGN KEY (nom_R) REFERENCES RAYONS (nom_R);
CREATE INDEX nom_index ON employes (nom);

ALTER TABLE ARTICLES
ADD CONSTRAINT FK_nom_Raarticles FOREIGN KEY (nom_R) REFERENCES RAYONS (nom_R);

CREATE INDEX type_A_index ON ARTICLES (type_A);

ALTER TABLE LIVRAISONS
ADD CONSTRAINT PK_code_A_code_F PRIMARY KEY(code_A,code_F),
ADD CONSTRAINT FK_code_F FOREIGN KEY (code_F) REFERENCES FOURNISSEURS (code_F),
ADD CONSTRAINT FK_code_A FOREIGN KEY (code_A) REFERENCES ARTICLES (code_A);







				

					






				

					
