USE exo_5_magasins;

DROP TABLE IF EXISTS VENTES;
DROP TABLE IF EXISTS MAGASINS;
DROP TABLE IF EXISTS RAYONS;
DROP TABLE IF EXISTS ARTICLES;

CREATE TABLE IF NOT EXISTS MAGASINS
(
	codeM INT PRIMARY KEY,
	nomM VARCHAR(50) NOT NULL	
);

CREATE TABLE IF NOT EXISTS RAYONS
(
	nomR VARCHAR(50) PRIMARY KEY 
);

CREATE TABLE IF NOT EXISTS ARTICLES
(
	codeA INT PRIMARY KEY,
	nomA VARCHAR(50) NOT NULL,
	typeA CHAR(1) NOT NULL 	
);

CREATE TABLE IF NOT EXISTS VENTES
(
	codeM INT,
	nomR VARCHAR(50) NOT NULL,
	codeA INT NOT NULL,
	quantite INT NOT NULL
);

ALTER TABLE VENTES
ADD CONSTRAINT FK_codeM FOREIGN KEY (codeM) REFERENCES MAGASINS (codeM),
ADD CONSTRAINT FK_nomR FOREIGN KEY (nomR) REFERENCES RAYONS (nomR),
ADD CONSTRAINT FK_codeA FOREIGN KEY (codeA) REFERENCES ARTICLES (codeA),
ADD CONSTRAINT PK_codeM_nomR_codeA PRIMARY KEY (codeM,nomR,codeA);

ALTER TABLE ARTICLES
ADD CONSTRAINT CK_typeA CHECK ( typeA IN ('P:papeterie','L:livre','D:disque'));
